### ISSUE TITLE
Fix: Document 

### ISSUE THREAD

**Issue by nhannht** [operandinc/typescript-sdk#12]
In your example [here](https://operand.ai/docs/getting-started)
![image](https://user-images.githubusercontent.com/69144096/217959698-b4b6902c-3306-4ab7-a692-aa9213e48553.png)
But actually in your source code 
![image](https://user-images.githubusercontent.com/69144096/217959974-66cdf5c1-6ed3-4c80-b39f-d7642f2fd1ff.png)
That why this line not work:
![image](https://user-images.githubusercontent.com/69144096/217960357-30812904-204d-418d-9b7f-6c0f63c5a8a2.png)
![image](https://user-images.githubusercontent.com/69144096/217960387-9eec1a77-2a35-45bc-b69f-afba96fcc5c3.png)

So actually working sample must be:
```js
import {
    operandClient,
    indexIDHeaderKey,
    ObjectService,
    ObjectType,
} from "@operandinc/sdk";
```

**Comment by Donwauchopex** [comment]
Thanks for catching this. I pushed a fix on the docs.
